[project]
name = "dsa-grinding"
version = "0.1.0"
description = "To study data structures, algorithms and python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]
